# Generated by Django 3.2.13 on 2022-06-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=280, unique=True)),
                ('clade', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 't_organism',
            },
        ),
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 't_protein_family',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=280, null=True)),
                ('tax_id', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 't_taxonomy',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=120, unique=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('length_of_sequence', models.PositiveIntegerField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='api.organism')),
            ],
            options={
                'db_table': 't_protein',
            },
        ),
        migrations.AddField(
            model_name='organism',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxonomy'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_coordinate', models.IntegerField()),
                ('stop_coordinate', models.IntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='api.protein')),
                ('protein_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proteinfamily')),
            ],
            options={
                'db_table': 't_domain',
                'unique_together': {('protein', 'protein_family', 'start_coordinate', 'stop_coordinate')},
            },
        ),
    ]
